#!/bin/bash
# Quick Start for Web UI V2

echo "=========================================="
echo "  Interview Assistant - Web UI V2"
echo "=========================================="
echo ""

# Get IP address
IP=$(hostname -I | awk '{print $1}')

echo "🌐 WEB UI V2 - PROFESSIONAL MOBILE VIEW"
echo ""
echo "✨ NEW FEATURES:"
echo "   • Syntax-highlighted code blocks"
echo "   • Real-time updates (SSE)"
echo "   • Clean dark theme"
echo "   • No terminal noise"
echo ""
echo "=========================================="
echo ""
echo "📱 QUICK START:"
echo ""
echo "1. Start Web Server (Terminal 1):"
echo "   cd /home/venkat/InterviewVoiceAssistant"
echo "   source venv/bin/activate"
echo "   python3 web/server.py"
echo ""
echo "2. Start Interview Assistant (Terminal 2):"
echo "   python3 main.py voice"
echo "   # or: python3 main.py text"
echo ""
echo "3. Open on Mobile:"
echo "   http://$IP:8000"
echo ""
echo "=========================================="
echo ""
echo "🧪 TEST IT NOW:"
echo "   python3 test_web_ui_v2.py"
echo ""
echo "📖 FULL GUIDE:"
echo "   cat WEB_UI_V2_GUIDE.md"
echo ""
echo "=========================================="
